### ISSUE TITLE
LoadConstant(ushort), LoadConstant(short), LoadConstant(sbyte) and LoadConstant(byte) are missing

### ISSUE THREAD

**Issue by Konard** [kevin-montrose/Sigil#41]
Is it ok? Or this is a bug?

**Comment by Konard** [comment]
Looks like it is possible to solve with combination of `LoadConstant(int)` and `Convert`: http://referencesource.microsoft.com/#System.Core/Microsoft/Scripting/Compiler/ILGen.cs,336

**Comment by n8allan** [comment]
Yes, there are no IL instructions for emitting those sizes, so a convert is necessary.  I'd recommend NOT supporting them by emitting multiple instructions since this is an emitter, not a compiler.  The semantics of the IL language should be represented 1:1, which is a line this library already pushes the boundary on in places.

**Comment by Konard** [comment]
So this is ok. Ok then.
